### ISSUE TITLE
Cache mediator width 

### ISSUE THREAD

**Issue by adam-coogan** [LoganAMorrison/Hazma.jl#1]
It is costly to recompute the mediator width every time a cross section function is called. Instead, should override `Base.setproperty!` for models to update a field storing the width. We will also need to hide the field from being set manually, including when the model is constructed.

**Comment by LoganAMorrison** [comment]
This type of behaviour seems tricky in `Julia`. At first go, I would begin to write something like:

```julia
mutable struct MyModel
    g::Float64
    width::Float64
end

function Base.setproperty!(model::MyModel, sym::Symbol, v)
    if sym == :g
        model.g = v # infinite recursion 
        model.width = # result of computing width
    elseif sym == :width
        throw("can't set width")
    else # fallback to getfield
        throw("no field '$sym'")
    end
end
```

However, this doesn't work because `model.g = ...` calls `setproperty!(model, :g, ...)` and you get infinite recursion. 

One thing we could do is just make the model immutable. Then the width can be computed at instantiation and we wouldn't have to worry about it every needing to change. This would require the User to make a new model when things need to be changed. 

The second option would be to override `getproperty` and maybe use memoization? i.e. cache the value of the width and the values of parameters, check if parameters have changed and recompute width if need.

**Comment by adam-coogan** [comment]
Good point, but it turns out it works if you use `setfield!`, which is analogous to what we do with `getproperty!` for `HiggsPortal` and `HeavyQuark`. You also need to define an inner constructor so `width` gets set when the object is created.

```julia
mutable struct MyModel
    g
    width

    function MyModel(g)
        model = new(g, 0.0)  # initialize all fields and set width to some value
        setfield!(model, :width, width(model))  # then compute the width
        return model
    end
end

width(model::MyModel) = model.g^2

function Base.setproperty!(model::MyModel, sym::Symbol, v)
    sym == :width && throw(error("can't set width"))

    setfield!(model, sym, v)  # set the field if it's not width
    setfield!(model, :width, width(model))  # update width
end
```

I think that we can have this version of `setproperty!` dispatch on `AbstractTheoryMediator`. It would be nice if there was a way to automatically generate the inner constructor, since it'll have the same form for every concrete type. Maybe with macros?

**Comment by adam-coogan** [comment]
Ok, I indeed figured out how to do this with macros! See 6b1af84527e64f926dde4296d8f1743798002c3e. To make a new theory containing a mediator, you can use
```julia
@make_mediator_theory HiggsPortal [:mχ, :ms, :gsχχ, :sinθ] AbstractScalarMediator
```
This protects the width field `Γ_med` from being overwritten and updates it whenever any of the other fields are changed, and when the struct is constructed. This should save a bit of boilerplate code in the long run, and was fun to write.

My implementation of `@make_mediator_theory` doesn't validate the constructor arguments. We could modify it to allow a validation function to be paired with each field, though.

**Comment by LoganAMorrison** [comment]
Excellent! That's perfect. I actually had a very similar though regarding the macro! Well done.

**Comment by adam-coogan** [comment]
Thanks! I also figured out how to deal with the validation, which is pretty cool.

**Comment by LoganAMorrison** [comment]
Awesome! Do you intend for people to eventually use `@make_mediator_theory` or is it just for internal use? If the former, then I think we should have some examples in the functions docs on how to use it. Maybe there is a way to also take care of the `Base.getproperty` for things like this in the macro too:

```julia
function Base.getproperty(mod::HiggsPortal, param::Symbol)
    if param == :gsff
        return mod.sinθ
    elseif param == :gsGG
        return 3 * mod.sinθ
    elseif param == :gsFF
        return -5 / 6 * mod.sinθ
    elseif param == :Λ
        return VH
    else
        return getfield(mod, param)
    end
end
```
