### ISSUE TITLE
Fix docs warning from constants.jl

### ISSUE THREAD

**Issue by adam-coogan** [LoganAMorrison/Hazma.jl#3]
For some reason, running `using Hazma` gives me a warning like this for every constant:
```julia
┌ Warning: Replacing docs for `Hazma.ELECTRON_MASS :: Union{}` in module `Hazma`
└ @ Base.Docs docs/Docs.jl:223
```
This is super annoying.

**Comment by LoganAMorrison** [comment]
I think this will happen if `constants.jl` is included multiple times?

**Comment by LoganAMorrison** [comment]
I removed all explicit imports aside from the main `Hazma.jl` file and I don't get this warnings.
